version: '3'

services:
  # Node.js application service
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
  #   depends_on:
  #     - swagger-ui

  # # Swagger UI service
  # swagger-ui:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.swaggerui
  #   ports:
  #     - "8080:8080"
